export const USER_WS_CONNECTION_START: 'USER_WS_CONNECTION_START' = 'USER_WS_CONNECTION_START';
export const USER_WS_CONNECTION_SUCCESS: 'USER_WS_CONNECTION_SUCCESS' = 'USER_WS_CONNECTION_SUCCESS';
export const USER_WS_CONNECTION_ERROR: 'USER_WS_CONNECTION_ERROR' = 'USER_WS_CONNECTION_ERROR';
export const USER_WS_CONNECTION_CLOSED: 'USER_WS_CONNECTION_CLOSED' = 'USER_WS_CONNECTION_CLOSED';
export const USER_WS_GET_ORDERS: 'USER_WS_GET_ORDERS' = 'USER_WS_GET_ORDERS';
export const USER_WS_SEND_MESSAGE: 'USER_WS_SEND_MESSAGE' = 'USER_WS_SEND_MESSAGE';
export const USER_WS_USER_NAME_UPDATE: 'USER_WS_USER_NAME_UPDATE' = 'USER_WS_USER_NAME_UPDATE';
